#!/usr/bin/env bash

set -eo pipefail

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _echo {
	echo "$1"
}

# -----------------------------------------------------------------------------

function install {
	# java jdk, gradle, serverless
	sudo apt install openjdk-11-jdk gradle libappindicator-dev -y
	java -version
	gradle -v
	jq --version
	# serverless
	npm install -g serverless
	serverless -v
	# commandbox (debian via apt)
	curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
	echo "deb https://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
	sudo apt-get update && sudo apt-get install apt-transport-https commandbox
	box install cfml-compiler
}

function help {
	printf "%s <task> [args]\n\nTasks:\n" "${0}"

	compgen -A function | grep -v "^_" | cat -n

	printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
